@startuml
actor Admin as "Admin"
actor Employee as "Karyawan"

package "Aplikasi Pengelolaan Barang Toko Elektronik" {
    
    usecase "Login" as UC1
    usecase "Kelola Data Barang" as UC2
    usecase "Lihat Laporan Stok" as UC3
    usecase "Lihat Data Barang" as UC4
    usecase "Catat Transaksi Penjualan" as UC5

    Admin --> UC1
    Admin --> UC2
    Admin --> UC3
    Employee --> UC1
    Employee --> UC4
    Employee --> UC5
}

@enduml